# TURN server configuration for WebRTCPhoneP2Pv2.0

# Listening port for STUN and TURN
listening-port=3478

# Use fingerprint mechanism for authentication
fingerprint

# Use long-term credential mechanism for authentication.
# This allows the use of a shared secret for all users.
lt-cred-mech

# The realm for authentication. 'auto' will use the server's hostname.
realm=auto

# A static secret that is used to generate the short-term credentials.
# This will be set by an environment variable.
static-auth-secret=${TURN_PASSWORD}

# Log file
log-file=stdout

# Be verbose
verbose
