server.port=8080
app.cors.allowed-origins=*
jwt.secret=11111111111111111111111111111111111111111111111111111

spring.datasource.url=jdbc:mariadb://${MARIADB_HOST}:3306/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USER}
spring.datasource.password=${MARIADB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=Pitikinm@yandex.ru
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# WebRTC Configuration
webrtc.stun.server.url=stun:stun.l.google.com:19302

# The TURN server URL provided to clients.
# 'coturn' is the service name inside Docker and only works for testing on the host machine.
# For testing on other devices, you MUST change this to the local IP of the host.
webrtc.turn.server.url=turn:192.168.1.50:3478
# Example for local network testing:
# webrtc.turn.server.url=turn:192.168.1.50:3478

webrtc.turn.secret=${TURN_PASSWORD}
# Initial admin user to be granted Admin role on startup
app.admin.initial-login=admin@admin.admin

kurento.ws.uri=${KURENTO_URL:ws://localhost:8888/kurento}

kurento.ws.uri=${KURENTO_URL:ws://localhost:8888/kurento}

app.baseUrl=http://localhost:8080
